### ISSUE TITLE
Building with TinyCC

### ISSUE THREAD

**Issue by wini3d** [FreeGLUTProject/freeglut#108]
Any tips on how to manually build the static library version using TinyCC or perhaps using CMake?

https://github.com/Kitware/CMake/blob/master/Modules/Compiler/TinyCC-C.cmake

**Comment by jtsiomb** [comment]
I never even heard of tinycc before. Unless you post specifically what you tried and how it failed, I can't help you.

**Comment by wini3d** [comment]
Hi @jtsiomb, I'm using Windows so..

1. Deleted android, blackberry, egl, osx and x11 folders from the src folder 
2. Deleted freeglutdll.def.in file, fg_version.h.in and gles_stub.c files
3. cd to the mswin directory, then `tcc -w -O2 -c -D_WIN32_WINNT=0x0500 -DWINVER=0x0500 -D_CRT_SECURE_NO_WARNINGS -DNEED_XPARSEGEOMETRY_IMPL -DFREEGLUT_STATIC -I..\..\include *.c ..\*.c ..\util\*.c`
4. Got `fg_cursor_mswin.c:73: error: 'GCL_HCURSOR' undeclared`

TinyC Compiler provided Win API headers (taken from MinGW-64 project) in their downloads here: http://download.savannah.gnu.org/releases/tinycc/

**Comment by jtsiomb** [comment]
Wow ok, that's one way to do it...

Well, you're even further from my domain. I'm not a windows user. But it looks like GCL_HCURSOR is part of the win32 API since windows 2000 (according to MSDN). Assuming your TCC toolchain will eventually link with user32.dll, you could just add the missing declarations yourself. Otherwise the only thing you could do (short of hacking freeglut to *not* use those win32 API calls), is to talk to tinycc developers about updating their headers.

Either way this is certainly not a freeglut issue, so I'm closing it, but feel free to continue posting if you think there's something else freeglut-related we could help you with.

Also since you're building freeglut from source anyway, why not use the latest release? 3.0.0 is quite old.

**Comment by wini3d** [comment]
Ok thanks, will also try the latest release.
