### ISSUE TITLE
android ES2 context initialization failure

### ISSUE THREAD

**Issue by mumin16** [FreeGLUTProject/freeglut#110]
this is simple freeglut sample for android:
https://github.com/mumin16/freeglut-android-example

es3 is mandatory? es2 context not initializing?
glutInitContextVersion (3, 0);

if there is no es3 in any phone, sample not work?

**Comment by mumin16** [comment]
![screen](https://user-images.githubusercontent.com/3465736/181084210-88e5575d-8a5a-4fb7-9d51-1575128d4a75.jpg)

**Comment by jtsiomb** [comment]
Is this a bug report on freeglut or that sample code?

I'm not familiar with the android backend at all, but I don't expect freeglut to impose any requirements on the version of OpenGL ES you can use.

**Comment by mumin16** [comment]
https://user-images.githubusercontent.com/3465736/181180277-3ab8840d-c0fa-4623-9c42-faf411b90032.mp4

screen is empty after home and/or overview navigation buttons click. i think that a bug.

**Comment by mumin16** [comment]
https://user-images.githubusercontent.com/3465736/181184237-957bd81f-a79b-4290-b1c8-a323ba0559f5.mp4

**Comment by jtsiomb** [comment]
Videos are not searchable. If there was some relevant error message in that log, please post the text. Also I'm deleting the first video because it's unrelated clutter. If you found a separate bug from the one you're reporting here, please open a separate bug report, so that both can be tracked.

As I said, I'm not familiar with (nor interested in) the android backend of freeglut, so I'm not going to try and solve any of this myself, I'm just helping facilitate the useful archival of these bugs, so that someone else might find them and try to solve them at some point.
