### ISSUE TITLE
How to render without screen? [ubuntu 18.04]

### ISSUE THREAD

**Issue by niyunsheng** [FreeGLUTProject/freeglut#123]
I got error 1 `reeglut failed to open display ''` when the following code is run:
```cpp
glutInit(&argc, 0);
```
My system is a ubuntu 18.04 server with no screen.

Do you know how to render without screen ?

**Comment by jtsiomb** [comment]
You don't have a DISPLAY environment variable set. Set it to ":0.0" and try again. Without it no X programs will be able to run, this is not a freeglut issue. Try with xlogo, xclock, or xdpyinfo, first to make sure you can talk to the X server.

Also you're supposed to pass the argument vector as the second argument to `glutInit`, not 0. If argc happens to be > 1, this will crash.

**Comment by niyunsheng** [comment]
@jtsiomb Thank for your reply.
I'm using a remote Linux server that **doesn't have a screen**.
Can I use freeglut in this case?

I tried using `export DISPLAY=:0.0` and `xclock`, outputs
```
No protocol specified
Error: Can't open display: :0.0
```
The reason is that no monitor is available, do you think whether freeglut is available in this case?

**Comment by jtsiomb** [comment]
Yes you should be able to still use it (and any other X client) with a remote X connection. In that case the display is your own X server, the remote machine runs the clients which connect to your X server for display.

The traditional way to do this, is to connect to the remote host (where the client should run) and `export DISPLAY=myhost:0.0` where `myhost` is the computer where the X server runs. This might be complicated to set up currently, because by default most X servers no longer accept remote connections (they are executed with `-nolisten` by default).

The way that will most likely work, is to connect through ssh to the machine where the clients should run, passing the `-X` option to ssh. Assuming X11 forwarding is not disabled on your side or the ssh server side, this should open an ssh connection and set up a tunnel for forwarding the X11 protocol back to your host. In this case DISPLAY will be set automatically, to something like `:11.0`, and X clients should be able to run and pop up on your X server.

**Comment by niyunsheng** [comment]
Thank you very much, a remote X11 display works!

**Comment by niyunsheng** [comment]
Thank you very much, a remote X11 forwarding works!
